version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-db
    restart: always
    networks:
      - my-network
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./api
    container_name: api-server
    restart: always
    networks:
      - my-network
    ports:
      - "5000"
    depends_on:
      - extract
    environment:
      - PYTHONUNBUFFERED=1

  extract:
    build: ./extract
    container_name: extract-job
    restart: no
    networks:
      - my-network
    depends_on:
      - mongo
    volumes:
      - mongo_data:/data/db
    environment:
      - PYTHONUNBUFFERED=1
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "31417:80"
    depends_on:
      - api
    networks:
      - my-network

volumes:
  mongo_data:

networks:
  my-network:
